In [1]:
from treelib import Tree

tree = Tree()
counter = 0
tree.create_node("START", counter)

i = 0
x = int(i / 3) + 1
y = int(i - int(i / 3) * 3) + 1
letter = 'X'
node_text = ""
node_text += '\033[1m'
node_text += letter + " (" + str(x) + " " + str(y) + ")"
node_text += '\033[0m'
tree.create_node(node_text, 1, parent=0)

i = 8
x = int(i / 3) + 1
y = int(i - int(i / 3) * 3) + 1
letter = 'Y'
node_text = ""
node_text += '\033[1m'
node_text += letter + " (" + str(x) + " " + str(y) + ")"
node_text += '\033[0m'
tree.create_node(node_text, 2, parent=1)

i = 1
x = int(i / 3) + 1
y = int(i - int(i / 3) * 3) + 1
letter = 'X'
node_text = ""
message = "+"
node_text += '\033[1m'
node_text += letter + " (" + str(x) + " " + str(y) + ")"
node_text += ' ' + message + '\033[0m'
tree.create_node(node_text, 3, parent=2)

i = 7
x = int(i / 3) + 1
y = int(i - int(i / 3) * 3) + 1
letter = 'X'
node_text = ""
message = "-"
node_text += '\033[1m'
node_text += letter + " (" + str(x) + " " + str(y) + ")"
node_text += ' ' + message + '\033[0m'
tree.create_node(node_text, 4, parent=2)

i = 5
x = int(i / 3) + 1
y = int(i - int(i / 3) * 3) + 1
letter = 'Y'
node_text = ""
message = "+"
node_text += '\033[1m'
node_text += letter + " (" + str(x) + " " + str(y) + ")"
node_text += ' ' + message + '\033[0m'
tree.create_node(node_text, 5, parent=4)

i = 6
x = int(i / 3) + 1
y = int(i - int(i / 3) * 3) + 1
letter = 'Y'
node_text = ""
message = "-"
node_text += '\033[1m'
node_text += letter + " (" + str(x) + " " + str(y) + ")"
node_text += ' ' + message + '\033[0m'
tree.create_node(node_text, 6, parent=4)

i = 7
x = int(i / 3) + 1
y = int(i - int(i / 3) * 3) + 1
letter = 'Y'
node_text = ""
message = "+"
node_text += '\033[1m'
node_text += letter + " (" + str(x) + " " + str(y) + ")"
node_text += ' ' + message + '\033[0m'
tree.create_node(node_text, 7, parent=3)

i = 4
x = int(i / 3) + 1
y = int(i - int(i / 3) * 3) + 1
letter = 'Y'
node_text = ""
message = "-"
node_text += '\033[1m'
node_text += letter + " (" + str(x) + " " + str(y) + ")"
node_text += ' ' + message + '\033[0m'
tree.create_node(node_text, 8, parent=3)

i = 2
x = int(i / 3) + 1
y = int(i - int(i / 3) * 3) + 1
letter = 'X'
node_text = ""
message = "+1"
node_text += '\033[1m'
node_text += letter + " (" + str(x) + " " + str(y) + ")"
node_text += ' ' + message + '\033[0m'
tree.create_node(node_text, 9, parent=7)

i = 5
x = int(i / 3) + 1
y = int(i - int(i / 3) * 3) + 1
letter = 'X'
node_text = ""
message = "-"
node_text += '\033[1m'
node_text += letter + " (" + str(x) + " " + str(y) + ")"
node_text += ' ' + message + '\033[0m'
tree.create_node(node_text, 10, parent=7)

i = 6
x = int(i / 3) + 1
y = int(i - int(i / 3) * 3) + 1
letter = 'Y'
node_text = ""
message = "-1"
node_text += '\033[1m'
node_text += letter + " (" + str(x) + " " + str(y) + ")"
node_text += ' ' + message + '\033[0m'
tree.create_node(node_text, 11, parent=10)

i = 5
x = int(i / 3) + 1
y = int(i - int(i / 3) * 3) + 1
letter = 'Y'
node_text = ""
message = "0"
node_text += '\033[1m'
node_text += letter + " (" + str(x) + " " + str(y) + ")"
node_text += ' ' + message + '\033[0m'
tree.create_node(node_text, 12, parent=10)

i = 2
x = int(i / 3) + 1
y = int(i - int(i / 3) * 3) + 1
letter = 'X'
node_text = ""
message = "+1"
node_text += '\033[1m'
node_text += letter + " (" + str(x) + " " + str(y) + ")"
node_text += ' ' + message + '\033[0m'
tree.create_node(node_text, 13, parent=8)

i = 6
x = int(i / 3) + 1
y = int(i - int(i / 3) * 3) + 1
letter = 'X'
node_text = ""
message = "-"
node_text += '\033[1m'
node_text += letter + " (" + str(x) + " " + str(y) + ")"
node_text += ' ' + message + '\033[0m'
tree.create_node(node_text, 14, parent=8)

i = 7
x = int(i / 3) + 1
y = int(i - int(i / 3) * 3) + 1
letter = 'Y'
node_text = ""
message = "+"
node_text += '\033[1m'
node_text += letter + " (" + str(x) + " " + str(y) + ")"
node_text += ' ' + message + '\033[0m'
tree.create_node(node_text, 15, parent=14)

tree.show()

START
└── X (1 1)
    └── Y (3 3)
        ├── X (1 2) +
        │   ├── Y (2 2) -
        │   │   ├── X (1 3) +1
        │   │   └── X (3 1) -
        │   │       └── Y (3 2) +
        │   └── Y (3 2) +
        │       ├── X (1 3) +1
        │       └── X (2 3) -
        │           ├── Y (2 3) 0
        │           └── Y (3 1) -1
        └── X (3 2) -
            ├── Y (2 3) +
            └── Y (3 1) -

In [6]:
import pandas as pd

data = {
    "x/u": ["x1", "x2", "x3", "x4"],
    "u1": ["+", "+", "+", "+"],
    "u2": ["+", "-", "-", "+"],
    "u3": ["+", "-", "+", "-"],
}
table = pd.DataFrame(data)
table

  x/u u1 u2 u3
0  x1  +  +  +
1  x2  +  -  -
2  x3  +  -  +
3  x4  +  +  -

In [8]:
data = {
    "x/v": ["y1", "y2", "y3", "y4", "y5", "y6"],
    "v1": ["+", "+", "+", "+", "+", "+"],
    "v2": ["+", "-", "+", "-", "+", "-"],
    "v3": ["+", "-", "-", "+", " ", " "],
}
table = pd.DataFrame(data)
table

  x/v v1 v2 v3
0  y1  +  +  +
1  y2  +  -  -
2  y3  +  +  -
3  y4  +  -  +
4  y5  +  +
5  y6  +  -

In [10]:
data = {
    " ": ["x1", "x2", "x3", "x4"],
    "y1": ["...", " ", " ", " "],
    "y2": ["1/9", " ", " ", " "],
    "y3": [" ", " ", " ", " "],
    "y4": [" ", " ", " ", " "],
    "y5": [" ", " ", " ", " "],
    "y6": [" ", " ", " ", " "],
}
table = pd.DataFrame(data)
table

        y1   y2 y3 y4 y5 y6
0  x1  ...  1/9
1  x2
2  x3
3  x4